Add type and color attributes to QrCode
I don't know why this is necessary but otherwise the type checker complains about the type not matching

```
src/components/UploadComponent.vue(117,42): error TS2322: Type '{ value: string; class: string; }' is not assignable to type 'ComponentProps<DefineComponent<{ version: { type: NumberConstructor; validator: (version: number) => boolean; }; errorCorrectionLevel: { type: PropType<QRCodeErrorCorrectionLevel>; validator: (level: QRCodeErrorCorrectionLevel) => boolean; }; maskPattern: { type: PropType<QRCodeMaskPattern>; validator: (maskPattern: QRCodeMaskPattern) => boolean; }; toSJISFunc: PropType<QRCodeToSJISFunc>; margin: NumberConstructor; scale: NumberConstructor; width: NumberConstructor; color: { type: ObjectConstructor; validator: (color: any) => boolean; required: true; }; type: { type: PropType<"image/png" | "image/jpeg" | "image/webp" | undefined>; validator: (type: any) => boolean; required: true; }; quality: { type: NumberConstructor; validator: (quality: number) => boolean; required: false; }; value: { type: PropType<string | QRCodeSegment[]>; required: true; validator(value: string | QRCodeSegment[]): boolean; }; }, () => VNode<RendererNode, RendererElement, { [key: string]: any; }>, unknown, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, string, VNodeProps & AllowedComponentProps & ComponentCustomProps, Readonly<ExtractPropTypes<{ version: { type: NumberConstructor; validator: (version: number) => boolean; }; errorCorrectionLevel: { type: PropType<QRCodeErrorCorrectionLevel>; validator: (level: QRCodeErrorCorrectionLevel) => boolean; }; maskPattern: { type: PropType<QRCodeMaskPattern>; validator: (maskPattern: QRCodeMaskPattern) => boolean; }; toSJISFunc: PropType<QRCodeToSJISFunc>; margin: NumberConstructor; scale: NumberConstructor; width: NumberConstructor; color: { type: ObjectConstructor; validator: (color: any) => boolean; required: true; }; type: { type: PropType<"image/png" | "image/jpeg" | "image/webp" | undefined>; validator: (type: any) => boolean; required: true; }; quality: { type: NumberConstructor; validator: (quality: number) => boolean; required: false; }; value: { type: PropType<string | QRCodeSegment[]>; required: true; validator(value: string | QRCodeSegment[]): boolean; }; }>>, {}>>'.
  Type '{ value: string; class: string; }' is missing the following properties from type 'Omit<Readonly<ExtractPropTypes<{ version: { type: NumberConstructor; validator: (version: number) => boolean; }; errorCorrectionLevel: { type: PropType<QRCodeErrorCorrectionLevel>; validator: (level: QRCodeErrorCorrectionLevel) => boolean; }; maskPattern: { type: PropType<QRCodeMaskPattern>; validator: (maskPattern: QRCodeMaskPattern) => boolean; }; toSJISFunc: PropType<QRCodeToSJISFunc>; margin: NumberConstructor; scale: NumberConstructor; width: NumberConstructor; color: { type: ObjectConstructor; validator: (color: any) => boolean; required: true; }; type: { type: PropType<"image/png" | "image/jpeg" | "image/webp" | undefined>; validator: (type: any) => boolean; required: true; }; quality: { type: NumberConstructor; validator: (quality: number) => boolean; required: false; }; value: { type: PropType<string | QRCodeSegment[]>; required: true; validator(value: string | QRCodeSegment[]): boolean; }; }>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>': type, color
```